#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    BACKEND-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^backend\.ddev\.site$`)
      
      service: "BACKEND-xhgui-80"
      tls: false
      # middlewares:
      #   - "BACKEND-redirectHttps"
    BACKEND-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^backend\.ddev\.site$`)
      
      service: "BACKEND-web-80"
      tls: false
      # middlewares:
      #   - "BACKEND-redirectHttps"
    BACKEND-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^backend\.ddev\.site$`)
      
      service: "BACKEND-web-8025"
      tls: false
      # middlewares:
      #   - "BACKEND-redirectHttps"
    
    
    BACKEND-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^backend\.ddev\.site$`)
      
      service: "BACKEND-xhgui-80"
      
      tls: true
      
    
    
    BACKEND-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^backend\.ddev\.site$`)
      
      service: "BACKEND-web-80"
      
      tls: true
      
    BACKEND-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^backend\.ddev\.site$`)
      
      service: "BACKEND-web-8025"
      
      tls: true
      
    

  middlewares:
    BACKEND-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    BACKEND-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-BACKEND-xhgui:80
        
    
    BACKEND-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-BACKEND-web:80
        
    BACKEND-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-BACKEND-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/BACKEND.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/BACKEND.key